ghash/CHANGES.md
ghash/Cargo.toml

ghash v0.1.0

---

polyval/benches/polyval.rs
polyval/src/lib.rs

@tarcieri  +~200MiB/s in my testing. Alternatively the consumer may enable LTO.

Copy UniversalHash::update_padded into Polyval's implementation + use black_box in benches

---

ghash/Cargo.toml
ghash/src/lib.rs
poly1305/Cargo.toml
poly1305/src/lib.rs
polyval/Cargo.toml
polyval/src/lib.rs

Upgrade to `universal-hash` crate v0.3

---

poly1305/README.md

Links to the `chacha20poly1305` and `xsalsa20poly1305` crates

poly1305: Update README.md with AEAD links

---

poly1305/CHANGES.md
poly1305/Cargo.toml

- Upgrade to `zeroize` 1.0 ([#33])
[#33]: https://github.com/RustCrypto/universal-hashes/pull/33

poly1305 v0.5.2

---

polyval/CHANGES.md
polyval/Cargo.toml

- Upgrade to `zeroize` 1.0 ([#33])
[#33]: https://github.com/RustCrypto/universal-hashes/pull/33

polyval v0.3.1

---

polyval/Cargo.toml
polyval/src/field.rs

There are probably better ways this could be leveraged, but this is at least an improvement over what it was.

polyval: Use `cfg-if` crate to reduce duplication

---

polyval/CHANGES.md
polyval/Cargo.toml

- Constant-time 32-bit software implementation ([#39])
- Use `cfg-if` crate to reduce duplication ([#40])
[#39]: https://github.com/RustCrypto/universal-hashes/pull/39
[#40]: https://github.com/RustCrypto/universal-hashes/pull/40

polyval v0.3.2

---

polyval/src/field.rs
polyval/src/field/pclmulqdq.rs

Move notes about the PCLMULQDQ-based implementation into `pclmulqdq.rs`

polyval: comment fixup

---

ghash/README.md
poly1305/README.md
polyval/README.md

Have them all start with "RustCrypto: *"

Make README.md headlines consistent

---

poly1305/tests/lib.rs

It was accidentally removed in #52.

poly1305: Re-add donna's self-test 2 test vector

---

poly1305/src/backend/avx2.rs
poly1305/src/backend/avx2/helpers.rs

Makes `cached_blocks` into a `[Block; 4]`, which eliminates a bunch of array offset calculations used in the previous byte array-based implementation.
We can rely on Rust layout to place these contiguously (i.e. `stride == size`):
https://github.com/rust-lang/unsafe-code-guidelines/blob/1c44b54/reference/src/layout/arrays-and-slices.md

poly1305: refactor AVX2 backend's cached blocks

---

Cargo.lock
polyval/CHANGELOG.md
polyval/Cargo.toml

- Performance improvements ([#75])
[#75]: https://github.com/RustCrypto/universal-hashes/pull/75

polyval v0.4.1

---

Cargo.lock
polyval/CHANGELOG.md
polyval/Cargo.toml
polyval/src/lib.rs

- CLMUL detection ([#92])
[#92]: https://github.com/RustCrypto/universal-hashes/pull/92

polyval v0.4.3

---

.github/workflows/polyval.yml

Make `autodetect` test normal feature combinations, and `soft` test combinations with the `force-soft` feature.

poly1305: split CI jobs for autodetect/soft

---

Cargo.lock
ghash/Cargo.toml
ghash/src/lib.rs
poly1305/Cargo.toml
poly1305/src/lib.rs
polyval/Cargo.toml
polyval/src/lib.rs

Provides a simple opaque `Debug` impl

Use `opaque-debug` to impl Debug for all crates

---

.github/workflows/ghash.yml
.github/workflows/poly1305.yml
.github/workflows/polyval.yml
.github/workflows/workspace.yml
Cargo.lock
Cargo.toml
README.md
ghash/CHANGELOG.md
ghash/Cargo.toml
ghash/README.md
poly1305/CHANGELOG.md
poly1305/Cargo.toml
poly1305/README.md
poly1305/src/backend/avx2.rs
poly1305/src/backend/avx2/helpers.rs
poly1305/src/backend/soft.rs
poly1305/src/lib.rs
polyval/CHANGELOG.md
polyval/Cargo.toml
polyval/README.md
polyval/src/backend/soft32.rs
polyval/src/backend/soft64.rs
polyval/src/lib.rs

Bump zeroize

---

Cargo.lock
polyval/CHANGELOG.md
polyval/Cargo.toml

Added
- add `new_with_init_block` (#195)
Changed
- implement Karatsuba multiplication for arm64 (#181)

polyval v0.6.2

---

README.md
ghash/README.md
poly1305/README.md
polyval/README.md

Add hazmat warnings

---

poly1305/src/backend/soft.rs

Small formatting of hex literal in soft.rs

---

poly1305/tests/lib.rs

Update test vector URL to match redirect

---

poly1305/src/backend/autodetect.rs
poly1305/src/backend/soft.rs
poly1305/src/lib.rs
polyval/src/backend/autodetect.rs
polyval/src/backend/soft32.rs
polyval/src/backend/soft64.rs

Reduces the multi-line function signatures to a single line

poly1305,polyval: import `UhfClosure` for better cosmetics
