RustCrypto/universal-hashes

.travis.yml, test_polyval.sh
The `polyval` crate presently needs either special `RUSTFLAGS` or non-default features.
I do intend to fix that (I have a half-finished pure software constant-time implementation which performs ~3X better than the current completely naive non-constant-time version) but for now I just want to get CI green.
=> .travis.yml: Fix build for `polyval` crate

README.md, poly1305/CHANGES.md, poly1305/Cargo.toml, poly1305/README.md, polyval/Cargo.toml, polyval/README.md
Several links in the README.md and `Cargo.toml` files need to be updated to reflect the new repository.
=> Fix links after move from RustCrypto/MACs

poly1305/Cargo.toml, poly1305/benches/poly1305.rs, poly1305/src/lib.rs, poly1305/tests/lib.rs
A first pass at adapting Poly1305 to use the `UniversalHash` trait
=> poly1305: Use UniversalHash trait

polyval/Cargo.toml, polyval/src/field/backend.rs, polyval/src/field/backend/soft.rs, polyval/src/ghash.rs, polyval/src/lib.rs, polyval/tests/lib.rs
Implements GHASH in terms of POLYVAL as described in RFC 8452 Appendix A:
https://tools.ietf.org/html/rfc8452#appendix-A
=> polyval: Implement GHASH

Cargo.toml, README.md, ghash/CHANGES.md, ghash/Cargo.toml, ghash/LICENSE-APACHE, ghash/LICENSE-MIT, ghash/README.md, ghash/benches/ghash.rs, ghash/src/lib.rs, ghash/tests/lib.rs, polyval/src/field/backend/soft.rs, polyval/src/lib.rs, polyval/tests/lib.rs
This extracts `ghash` into its own crate.
In attempting to add runtime detection to `polyval`, having `ghash` in the same crate felt in-the-way. In this commit, I have split the two crates in advance, and then I'll rebase my runtime detection into its own commit.
I think we only need two crates here, as the `ghash` crate is implemented in terms of POLYVAL's field/polynomial:
`GHASH(H, X_1, ..., X_n)` =>
`ByteReverse(POLYVAL(mulX_POLYVAL(ByteReverse(H)), ByteReverse(X_1), ..., ByteReverse(X_n)))`
Though they both operate over GF(2^128), there are some slight discrepancies in the field arithmetic owing to the polynomial, and this approach leverages the fact that the POLYVAL polynomial is the "reverse" of the GHASH one.
=> ghash: Split from `polyval` crate

polyval/src/field.rs, polyval/src/field/backend.rs, polyval/src/field/pclmulqdq.rs, polyval/src/field/soft.rs, polyval/src/lib.rs
Eliminate needless traits and module depth, making `field::Element` into a simple newtype wrapper.
=> polyval: Simplify implementation

polyval/src/field/backend.rs
Accidentally left over after #12. No longer used.
=> polyval: Removed unused file

ghash/CHANGES.md, ghash/Cargo.toml, polyval/CHANGES.md, polyval/Cargo.toml, polyval/src/field.rs
- Constant time software implementation ([#7])
- Update to Rust 2018 edition ([#3])
- Use `UniversalHash` trait ([#6])
- Removed generics/traits from `field::Element` API ([#12])
- `insecure-soft` cargo feature ([#7])
[#3]: https://github.com/RustCrypto/universal-hashes/pull/3
[#6]: https://github.com/RustCrypto/universal-hashes/pull/6
[#7]: https://github.com/RustCrypto/universal-hashes/pull/7
[#12]: https://github.com/RustCrypto/universal-hashes/pull/12
=> polyval v0.1.0

poly1305/CHANGES.md, poly1305/Cargo.toml
- Update to Rust 2018 edition ([#3])
- Use `UniversalHash` trait ([#5])
[#3]: https://github.com/RustCrypto/universal-hashes/pull/3
[#5]: https://github.com/RustCrypto/universal-hashes/pull/5
=> poly1305 v0.4.0

poly1305/src/lib.rs
Alias for `Output<U16>`.
Based on TODO from this PR:
https://github.com/RustCrypto/AEADs/pull/8/files#diff-fdc13efdc7d664b91b2edc4e61ea2662R17
=> poly1305: Add `Tag` type

poly1305/CHANGES.md, poly1305/Cargo.toml
- Upgrade to `zeroize` v1.0.0-pre ([#19])
[#19]: https://github.com/RustCrypto/universal-hashes/pull/19
=> poly1305 v0.4.1

polyval/CHANGES.md, polyval/Cargo.toml
- Upgrade to `zeroize` v1.0.0-pre ([#19])
[#19]: https://github.com/RustCrypto/universal-hashes/pull/19
=> polyval v0.1.1

poly1305/CHANGES.md, poly1305/Cargo.toml
- Upgrade to `universal-hash` crate v0.3 ([#22])
[#22]: https://github.com/RustCrypto/universal-hashes/pull/22
=> poly1305 v0.5.0

ghash/Cargo.toml, polyval/CHANGES.md, polyval/Cargo.toml
- Upgrade to `universal-hash` crate v0.3 ([#22])
[#22]: https://github.com/RustCrypto/universal-hashes/pull/22
=> polyval v0.2.0

ghash/CHANGES.md, ghash/Cargo.toml, ghash/src/lib.rs
- Upgrade to `polyval` v0.2 and `universal-hash` crate v0.3 ([#22])
[#22]: https://github.com/RustCrypto/universal-hashes/pull/22
=> ghash v0.2.0

poly1305/CHANGES.md, poly1305/Cargo.toml
- Link to `chacha20poly1305` and `xsalsa20poly1305` crates from README.md ([#26])
[#26]: https://github.com/RustCrypto/universal-hashes/pull/26
=> poly1305 v0.5.1

ghash/Cargo.toml, ghash/src/lib.rs, polyval/benches/polyval.rs, polyval/src/field.rs, polyval/src/lib.rs
We don't actually need to expose this, even for `ghash`.
Keeping it out of the public API until we actually have a legitimate use case for exposing it will increase flexibility when we do want to.
=> polyval: Remove `pub` from `field` module

ghash/Cargo.toml, polyval/CHANGES.md, polyval/Cargo.toml
- Remove `pub` from `field` module ([#28])
[#28]: https://github.com/RustCrypto/universal-hashes/pull/28
=> polyval v0.3.0

ghash/CHANGES.md, ghash/Cargo.toml
- Upgrade to `polyval` v0.3 ([#29])
[#29]: https://github.com/RustCrypto/universal-hashes/pull/29
=> ghash v0.2.1

ghash/src/lib.rs
These changes broke the implementation of `mulX_POLYVAL`:
https://github.com/RustCrypto/universal-hashes/pull/28/files#diff-6189716e3235b5dfb266bd1c39947b1aR95
After reverting it, AES-GCM test vectors which previously failed are now working:
https://github.com/RustCrypto/AEADs/pull/26
=> ghash: Revert mulX_POLYVAL changes from #28

ghash/CHANGES.md, ghash/Cargo.toml
- Revert mulX_POLYVAL changes from #28 ([#31])
[#31]: https://github.com/RustCrypto/universal-hashes/pull/31
=> ghash v0.2.2

ghash/Cargo.toml, poly1305/Cargo.toml, polyval/Cargo.toml
This removes the `-pre` from the requirements for all crates which are using it.
Due to semver all of these crates are already using `zeroize` 1.0. This commit just clarifies which versions are used by updating the requirement to suit.
=> Upgrade to `zeroize` 1.0

ghash/CHANGES.md, ghash/Cargo.toml
- Upgrade to `zeroize` 1.0 ([#33])
[#33]: https://github.com/RustCrypto/universal-hashes/pull/33
=> ghash v0.2.3

polyval/benches/polyval.rs, polyval/src/field.rs, polyval/src/field/u32_soft.rs, polyval/src/field/u64_soft.rs
Previously (in #7) BearSSL's `ghash_ctmul64.c` was adapted into a portable software backend.
This commit additionally adapts BearSSL's `ghash_ctmul32.c` into a portable constant-time field arithmetic backend for POLYVAL designed for 32-bit architectures.
=> polyval: Constant-time 32-bit software implementation

polyval/src/field.rs, polyval/src/field/pclmulqdq.rs
Previously the implementation used the `_mm_shuffle_pd` intrinsic which maps to the `shufpd` (floating point shuffle) instruction.
This still produced the correct assembly (i.e. `pshufd`), as LLVM noticed the inputs and outputs were integers and substituted `pshufd` for `shufpd`, which is the correct ASM according to this QuarksLab blog post:
https://blog.quarkslab.com/reversing-a-finite-field-multiplication-optimization.html
This changes the code to call the proper `pshufd` intrinsic directly (`_mm_shuffle_epi32`), which is cleaner.
=> Use correct `pshufd` intrinsic

polyval/src/field/pclmulqdq.rs
The previous implementation used separate `#[target_feature(...)]` blocks for each `core::arch` intrinsic. This thwarts the inliner, so these all translated to `call` instructions.
This change inlines the intrinsic calls into larger `#[target_feature(...)]`-gated functions.
When compiling with `-C target-cpu=skylake`, the generated assembly matches the idealized version (for at least the Montgomery fast reduction) as described in this QuarksLab blog post:
https://blog.quarkslab.com/reversing-a-finite-field-multiplication-optimization.html
Their version:
Godbolt: https://godbolt.org/z/Zjuvwu
=> polyval: match ideal assembly

polyval/CHANGES.md, polyval/Cargo.toml
- Match ideal assembly implementation on x86/x86_64 ([#43], [#44])
[#43]: https://github.com/RustCrypto/universal-hashes/pull/43
[#44]: https://github.com/RustCrypto/universal-hashes/pull/44
=> polyval v0.3.3

poly1305/src/lib.rs, poly1305/src/soft.rs
Makes the implementation more readable, sets the ground for #46, and also improves performance a bit!
=> Poly1305 refactor

Cargo.lock, ghash/src/lib.rs, ghash/tests/lib.rs, poly1305/src/lib.rs, poly1305/tests/lib.rs, polyval/src/lib.rs, polyval/tests/lib.rs
Implements the API changes from:
https://github.com/RustCrypto/traits/pull/161
The `universal-hash` crate now uses `update` and `finalize` nomenclature ala the Initialize-Update-Finalize (IUF) interface naming scheme.
=> Rename `*result*` to `finalize`

Cargo.lock, poly1305/CHANGELOG.md, poly1305/Cargo.toml
- `Poly1305::compute_unpadded` for XSalsa20Poly1305 ([#55])
- Bump `universal-hash` dependency to v0.4; MSRV 1.41 ([#52], [#57])
- Rename `result` methods to to `finalize` ([#56])
- Build with `zeroize` enabled ([#48])
[#57]: https://github.com/RustCrypto/universal-hashes/pull/57
[#56]: https://github.com/RustCrypto/universal-hashes/pull/56
[#55]: https://github.com/RustCrypto/universal-hashes/pull/55
[#52]: https://github.com/RustCrypto/universal-hashes/pull/52
[#48]: https://github.com/RustCrypto/universal-hashes/pull/48
=> poly1305 v0.6.0

Cargo.lock, ghash/Cargo.toml, polyval/CHANGELOG.md, polyval/Cargo.toml
- Bump `universal-hash` dependency to v0.4; MSRV 1.41 ([#52], [#57])
- Rename `result` methods to to `finalize` ([#56])
[#57]: https://github.com/RustCrypto/universal-hashes/pull/57
[#56]: https://github.com/RustCrypto/universal-hashes/pull/56
[#52]: https://github.com/RustCrypto/universal-hashes/pull/52
=> polyval v0.4.0

Cargo.lock, ghash/CHANGES.md, ghash/Cargo.toml
- Bump `polyval` dependency to v0.4 ([#59])
- Bump `universal-hash` dependency to v0.4; MSRV 1.41 ([#52], [#57])
- Rename `result` methods to to `finalize` ([#56])
[#59]: https://github.com/RustCrypto/universal-hashes/pull/59
[#57]: https://github.com/RustCrypto/universal-hashes/pull/57
[#56]: https://github.com/RustCrypto/universal-hashes/pull/56
[#52]: https://github.com/RustCrypto/universal-hashes/pull/52
=> ghash v0.3.0

README.md
All three crates in this repo were audited by NCC group:
https://research.nccgroup.com/2020/02/26/public-report-rustcrypto-aes-gcm-and-chacha20poly1305-implementation-review/
While the individual README.mds for each crate were updated to reflect this, it seems the toplevel README.md was missed.
=> README.md: remove warning (all crates were audited!)

.github/workflows/workspace.yml
No longer needs a `CODECOV_TOKEN`
=> .github: use latest Tarpaulin; bump codecov-action

Cargo.lock, poly1305/CHANGELOG.md, poly1305/Cargo.toml, poly1305/README.md, poly1305/src/lib.rs
- AVX2 backend ([#49])
[#49]: https://github.com/RustCrypto/universal-hashes/pull/49
=> poly1305 v0.6.1

Cargo.lock, polyval/CHANGELOG.md, polyval/Cargo.toml
- `KEY_SIZE` constant ([#82])
- Bump `cfg-if` from v0.1 to v1.0.0 ([#86])
[#86]: https://github.com/RustCrypto/universal-hashes/pull/86
[#82]: https://github.com/RustCrypto/universal-hashes/pull/82
=> polyval v0.4.2

.github/workflows/poly1305.yml, Cargo.lock, poly1305/Cargo.toml, poly1305/src/autodetect.rs, poly1305/src/backend.rs, poly1305/src/backend/avx2.rs, poly1305/src/backend/avx2/helpers.rs, poly1305/src/backend/soft.rs, poly1305/src/fuzz.rs, poly1305/src/lib.rs
Automatically detects the availability of CLMUL based on CPUID, and falls back to the "soft" implementation if unavailable.
=> poly1305: AVX2 detection

Cargo.lock, poly1305/CHANGELOG.md, poly1305/Cargo.toml
- AVX2 backend ([#49])
[#49]: https://github.com/RustCrypto/universal-hashes/pull/49
=> poly1305 v0.6.2

polyval/src/autodetect.rs, polyval/src/backend/soft32.rs, polyval/src/backend/soft64.rs
Adds a `Drop` impl for the autodetect backend which zeroizes when the `zeroize` feature is enabled.
Due to the need for union members to be `Copy` until we can leverage `ManuallyDrop` on MSRV 1.49+, the `soft` backends still don't implement it properly.
This commit also adds a TODO to fix that when we bump MSRV.
=> polyval: fix `zeroize` feature on autodetect backend

poly1305/src/lib.rs
The performance with autodetection enabled is nearly identical to the performance when passing explicit `target-cpu`/`target-flags`, so it's now irrelevant to note it.
=> poly1305: remove performance notes

Cargo.lock, polyval/CHANGELOG.md, polyval/Cargo.toml, polyval/src/lib.rs
- `mulx` feature ([#107])
[#107]: https://github.com/RustCrypto/universal-hashes/pull/107
=> polyval v0.4.4

ghash/Cargo.toml, ghash/src/lib.rs, ghash/tests/lib.rs, polyval/src/backend.rs
The `ghash` crate is implemented in terms of POLYVAL using a technique described in RFC 8452 Appendix A.
Part of this implementation is a multiply-by-x operation over POLYVAL field elements (a.k.a. `mulX_POLYVAL` in RFC 8452 terminology), which was previously defined in the `ghash` crate itself.
However, this function was just added to the `polyval` crate in #107, so the `ghash` crate can now use that implementation.
=> ghash: use `polyval::mulx`

Cargo.lock, ghash/CHANGELOG.md, ghash/Cargo.toml, polyval/CHANGELOG.md
- `Debug` impl using `opaque-debug` ([#105])
- Use `polyval::mulx` ([#109])
[#105]: https://github.com/RustCrypto/universal-hashes/pull/105
[#109]: https://github.com/RustCrypto/universal-hashes/pull/109
=> ghash v0.3.1

polyval/src/mulx.rs
Switches the internal implementation of `mulx()` from `u64` to `u128`.
In addition to the test vectors added in #107, this change was further integration tested against the `aes-gcm` crate, which contains a full set of NIST test vectors.
=> polyval: use u128 to impl `mulx`

Cargo.lock, polyval/CHANGELOG.md, polyval/Cargo.toml
- Use `u128` to impl `mulx` ([#111])
[#111]: https://github.com/RustCrypto/universal-hashes/pull/111
=> polyval v0.4.5

.github/workflows/ghash.yml, .github/workflows/polyval.yml, Cargo.lock, ghash/Cargo.toml, polyval/Cargo.toml, polyval/README.md, polyval/src/backend/autodetect.rs, polyval/src/backend/clmul.rs, polyval/src/backend/soft32.rs, polyval/src/backend/soft64.rs
Using `ManuallyDrop` for the fields of `union`s (allowing them to be non-Copy types) was stabilized in Rust 1.49.
=> polyval: use ManuallyDrop unions; MSRV 1.49+

.github/workflows/poly1305.yml, .github/workflows/workspace.yml, README.md, ghash/README.md, poly1305/README.md, poly1305/src/backend/autodetect.rs, poly1305/src/backend/avx2.rs, poly1305/src/backend/soft.rs, poly1305/src/lib.rs, polyval/src/backend/autodetect.rs, polyval/src/lib.rs
Using `ManuallyDrop` for the fields of `union`s (allowing them to be non-Copy types) was stabilized in Rust 1.49.
=> poly1305: use ManuallyDrop unions; MSRV 1.49+

Cargo.lock, poly1305/CHANGELOG.md, poly1305/Cargo.toml
- Use `ManuallyDrop` unions; MSRV 1.49+ ([#114])
- Use `cpufeatures` v0.1 crate release ([#116])
[#114]: https://github.com/RustCrypto/universal-hashes/pull/114
[#116]: https://github.com/RustCrypto/universal-hashes/pull/116
=> poly1305 v0.7.0

.github/workflows/polyval.yml, ghash/Cargo.toml, polyval/Cargo.toml, polyval/src/lib.rs, polyval/src/mulx.rs
There's really no reason this needs its own crate feature. Instead it is now a standard part of this crate's API.
=> polyval: remove `mulx` feature

Cargo.lock, ghash/Cargo.toml, polyval/CHANGELOG.md, polyval/Cargo.toml
- Use `ManuallyDrop` unions; MSRV 1.49+ ([#113], [#114])
- Replace `cpuid-bool` with `cpufeatures` ([#116])
- `mulx` feature: now always built-in ([#118])
[#113]: https://github.com/RustCrypto/universal-hashes/pull/113
[#114]: https://github.com/RustCrypto/universal-hashes/pull/114
[#116]: https://github.com/RustCrypto/universal-hashes/pull/116
[#118]: https://github.com/RustCrypto/universal-hashes/pull/118
=> polyval v0.5.0

Cargo.lock, ghash/CHANGELOG.md, ghash/Cargo.toml
- Bump `polyval` crate dependency to v0.5; MSRV 1.49+ ([#114], [#119])
[#114]: https://github.com/RustCrypto/universal-hashes/pull/114
[#119]: https://github.com/RustCrypto/universal-hashes/pull/119
=> ghash v0.4.0

.github/workflows/ghash.yml, ghash/Cargo.toml
=> ghash: add `force-soft` feature

Cargo.lock, ghash/CHANGELOG.md, ghash/Cargo.toml
- `force-soft` feature ([#121])
[#121]: https://github.com/RustCrypto/universal-hashes/pull/121
=> ghash v0.4.1

Cargo.lock, ghash/CHANGELOG.md, ghash/Cargo.toml
- Nightly-only ARMv8 intrinsics support gated under the `armv8` feature ([#126])
[#126]: https://github.com/RustCrypto/universal-hashes/pull/126
=> ghash v0.4.2

Cargo.lock, ghash/CHANGELOG.md, ghash/Cargo.toml, ghash/src/lib.rs, poly1305/CHANGELOG.md, poly1305/Cargo.toml, poly1305/src/lib.rs, polyval/CHANGELOG.md, polyval/Cargo.toml, polyval/src/lib.rs
Also updates Cargo.lock and makes the `#![doc(...)]` attribute consistent across crates.
=> Pin zeroize to v1.3

ghash/Cargo.toml
Allows all 1.0 versions of `zeroize` earlier than 1.4 (MSRV 1.51+)
=> ghash: relax zeroize constraints

Cargo.lock, ghash/CHANGELOG.md, ghash/Cargo.toml
- Relax `zeroize` constraints ([#141])
[#141]: https://github.com/RustCrypto/universal-hashes/pull/141
=> ghash v0.4.4

polyval/CHANGELOG.md, polyval/src/backend/autodetect.rs, polyval/src/backend/clmul.rs
As far as I can see none of the intrinsics used in the `mul` method require SSE4.1. inspecting generated assembly with this change does not show any uninlined intrinsics.
=> polyval: remove sse4.1 requirement

.github/workflows/workspace.yml
The lack of override directives in the workspace config means newer rustc versions than intended are being used which breaks the build: #149
Codecov hasn't been terribly helpful and adds to build times / spam. This commit removes it.
=> CI: fix workspace `override` directives; remove codecov

.github/workflows/ghash.yml, .github/workflows/poly1305.yml, .github/workflows/polyval.yml
The build is currently failing:
https://github.com/RustCrypto/universal-hashes/runs/5629586918?check_suite_focus=true
It's for two reasons:
1. `aarch64_target_feature` was recently stabilized in rust-lang/rust#90621 but we still include it
2. There's a bug relating to `neon`/`fp` activation. See rust-lang/rust#91608 and rust-lang/rust#95044
Until one of the fixes in the second issue is merged, we can't really make progress. So this commit pins to `nightly-2022-03-01` so we can continue to have a clean build.
Once either of the above solutions lands we can remove `aarch64_target_feature` and unpin nightly again.
=> polyval: pin `nightly` version used for ARMv8 testing

.github/workflows/polyval.yml, polyval/src/lib.rs
Removes the explicit `feature` annotation since the feature has been stabilized now.
Also unpins nightly, which was previously pinned as changes relating to `aarch64_target_feature` were causing nightly breakages. Everything's good to go now, though!
=> polyval: use stable `aarch64_target_feature`

.github/workflows/poly1305.yml, .github/workflows/polyval.yml, Cargo.lock, ghash/Cargo.toml, ghash/benches/ghash.rs, ghash/src/lib.rs, ghash/tests/lib.rs, poly1305/Cargo.toml, poly1305/benches/poly1305.rs, poly1305/src/backend/autodetect.rs, poly1305/src/backend/avx2.rs, poly1305/src/backend/avx2/helpers.rs, poly1305/src/backend/soft.rs, poly1305/src/fuzz.rs, poly1305/src/lib.rs, poly1305/tests/lib.rs, polyval/Cargo.toml, polyval/benches/polyval.rs, polyval/src/backend/autodetect.rs, polyval/src/backend/clmul.rs, polyval/src/backend/pmull.rs, polyval/src/backend/soft32.rs, polyval/src/backend/soft64.rs, polyval/src/lib.rs, polyval/tests/lib.rs
Continuation of #153. Migrates all crates to the initial prerelease of `universal-hash` v0.5.
=> Migrate to `universal-hash` v0.5.0-pre

polyval/src/backend/autodetect.rs, polyval/src/backend/clmul.rs, polyval/src/backend/pmull.rs, polyval/src/backend/soft32.rs, polyval/src/backend/soft64.rs
This is useful in the implementation of `aes-gcm-siv`, as it allows for calling the newly re-added `finalize_reset` method, which is useful to avoid consuming `self` when computing the tag.
SIV mode encryption requires first computing the tag as a pass of POLYVAL over the plaintext, where the tag also functions as a synthetic initialization vector. With AES-GCM-SIV specifically, it also needs access to the original nonce, which is XORed into the tag.
Consuming `self` means it's not possible to store the cipher, POLYVAL, and nonce in the same struct, since after computing the SIV tag it needs to be passed to the cipher.
=> polyval: impl `Reset`

Cargo.lock, ghash/Cargo.toml, poly1305/Cargo.toml, polyval/Cargo.toml
These prereleases use `universal-hash` v0.5.0-pre.1:
- `ghash` v0.5.0-pre.1
- `poly13095` v0.8.0-pre.1
- `polyval` v0.6.0-pre.1
=> Cut `-pre.1` releases

Cargo.lock, poly1305/Cargo.toml, poly1305/src/backend/avx2.rs, polyval/Cargo.toml
This adds `UhfBackend::blocks_needed_to_align` and impls it for the AVX2 backend of Poly1305.
=> Bump `universal-hash` to v0.5.0-pre.2

.github/workflows/poly1305.yml, .github/workflows/polyval.yml, ghash/Cargo.toml, poly1305/Cargo.toml, poly1305/src/backend.rs, poly1305/src/lib.rs, polyval/Cargo.toml, polyval/src/backend.rs, polyval/src/backend/autodetect.rs, polyval/src/lib.rs
Following the changes in e.g. the `aes` crate, this replaces cargo features for this functionality with attributes which can be provided in the toplevel build configuration as arguments to rustc:
- poly1305: `poly1305_force_soft`
- polyval: `polyval_armv8`, `polyval_force_soft`
This follows a similar naming scheme in the `aes` crate: `aes_force_soft`
It would probably make sense to consolidate these so we have the samenames across crates like `aes` and `polyval` so it could be activated with a single attribute, e.g. `rustcrypto_armv8`/`rustcrypto_force_soft`
However, for consistency this uses a similar scheme to what is already released in the `aes` crate.
=> Replace `armv8`/`force-soft` features with `cfg` attributes

Cargo.lock, ghash/Cargo.toml, poly1305/Cargo.toml, polyval/Cargo.toml
These prereleases use `universal-hash` v0.5.0-pre.2:
- `ghash` v0.5.0-pre.2
- `poly13095` v0.8.0-pre.2
- `polyval` v0.6.0-pre.2
=> Cut `-pre.2` releases

Cargo.lock, poly1305/Cargo.toml, polyval/Cargo.toml
Release notes: https://github.com/RustCrypto/traits/pull/1061
=> Bump `universal-hash` to v0.5

Cargo.lock, poly1305/CHANGELOG.md, poly1305/Cargo.toml
- Relax `zeroize` constraints ([#147])
- Upgrade to Rust 2021 edition ([#147])
- Use stable `aarch64_target_feature` ([#154])
- Bump `universal-hash` to v0.5 ([#155], [#162])
- Replace `armv8`/`force-soft` features with `cfg` attributes ([#159])
- `armv8`/`force-soft` features ([#159])
[#147]: https://github.com/RustCrypto/universal-hashes/pull/147
[#154]: https://github.com/RustCrypto/universal-hashes/pull/154
[#155]: https://github.com/RustCrypto/universal-hashes/pull/155
[#159]: https://github.com/RustCrypto/universal-hashes/pull/159
[#162]: https://github.com/RustCrypto/universal-hashes/pull/162
=> poly1305 v0.8.0

Cargo.lock, ghash/Cargo.toml, polyval/CHANGELOG.md, polyval/Cargo.toml
- Impl `Reset` ([#157])
- Remove `sse4.1` from CPU feature requirements for PCLMUL backend ([#143])
- Relax `zeroize` constraints ([#147])
- Upgrade to Rust 2021 edition ([#147])
- Use stable `aarch64_target_feature` ([#154])
- Replace `armv8`/`force-soft` features with `cfg` attributes ([#159])
- Bump `universal-hash` to v0.5 ([#155], [#162])
[#143]: https://github.com/RustCrypto/universal-hashes/pull/143
[#147]: https://github.com/RustCrypto/universal-hashes/pull/147
[#154]: https://github.com/RustCrypto/universal-hashes/pull/154
[#155]: https://github.com/RustCrypto/universal-hashes/pull/155
[#157]: https://github.com/RustCrypto/universal-hashes/pull/157
[#159]: https://github.com/RustCrypto/universal-hashes/pull/159
[#162]: https://github.com/RustCrypto/universal-hashes/pull/162
=> polyval v0.6.0

Cargo.lock, ghash/CHANGELOG.md, ghash/Cargo.toml
- Relax `zeroize` constraints ([#147])
- Upgrade to Rust 2021 edition ([#147])
- Replace `armv8`/`force-soft` features with `cfg` attributes ([#159])
- Bump `polyval` to v0.6.0 ([#164])
[#147]: https://github.com/RustCrypto/universal-hashes/pull/147
[#159]: https://github.com/RustCrypto/universal-hashes/pull/159
[#164]: https://github.com/RustCrypto/universal-hashes/pull/164
=> ghash v0.5.0

.github/workflows/ghash.yml, .github/workflows/poly1305.yml, .github/workflows/polyval.yml, .github/workflows/workspace.yml
Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/RustCrypto/block-modes/actions/runs/4369747458:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1, actions-rs/cargo@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of those warnings the occurrences of `actions-rs/toolchain` are replaced by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain), and the occurrences of `actions-rs/cargo` are replaced by direct invocations …
=> Replace unmaintained actions-rs/* actions in CI workflows

polyval/src/lib.rs
All of the functionality needed for the ARMv8 backend has been stabilized as of Rust 1.61.
This removes the superfluous use of `feature(stdsimd)` and updates the relevant documentation.
=> polyval: support `polyval_armv8` on Rust 1.61+

Cargo.lock, polyval/CHANGELOG.md, polyval/Cargo.toml, polyval/LICENSE-MIT, polyval/README.md
- Support for `polyval_armv8` on Rust 1.61+ ([#179])
[#179]: https://github.com/RustCrypto/universal-hashes/pull/179
=> polyval v0.6.1

polyval/src/backend/pmull.rs
Improves performance by ~200 MB/s on a 2020 M1.
=> polyval: implement Karatsuba multiplication for arm64

ghash/src/lib.rs, ghash/tests/lib.rs, polyval/src/backend/autodetect.rs, polyval/src/backend/clmul.rs, polyval/src/backend/pmull.rs, polyval/src/backend/soft32.rs, polyval/src/backend/soft64.rs
Add creation function for init_block, needed for `belt-dwp` AEAD
https://rustcrypto.zulipchat.com/#narrow/stream/260038-AEADs/topic/belt-dwp/near/418639333
=> add new_with_init_block

Cargo.lock, ghash/CHANGELOG.md, ghash/Cargo.toml
Added
- add `new_with_init_block` (#195)
=> ghash v0.5.1

poly1305/Cargo.toml, polyval/Cargo.toml
=> poly1305+polyval: add `lints.rust.unexpected_cfgs`

Cargo.lock, poly1305/src/fuzz.rs, poly1305/src/lib.rs, poly1305/tests/lib.rs, polyval/src/mulx.rs
Updates the following dependencies:
$ cargo update
Updating crates.io index
Locking 5 packages to latest compatible versions
Updating getrandom v0.2.12 -> v0.2.15
Updating hybrid-array v0.2.0-rc.7 -> v0.2.0-rc.9
Updating libc v0.2.149 -> v0.2.155
Updating subtle v2.5.0 -> v2.6.1
Also: fix hybrid-array deprecation warnings
=> Cargo.lock: bump dependencies

Cargo.lock, ghash/Cargo.toml, poly1305/Cargo.toml, polyval/Cargo.toml
Releases the following crates:
- `ghash` v0.6.0-rc.0
- `poly1305` v0.9.0-rc.0
- `polyval` v0.7.0-rc.0
=> Cut release candidates

polyval/src/backend/pmull.rs
`poly` can be defined as a constant at a file level and it doesn't need to be recalculated inside the function as it is an hardcoded value.
=> define poly const in polyval pmull

Cargo.lock, ghash/Cargo.toml, ghash/src/lib.rs, polyval/src/backend.rs, polyval/src/backend/autodetect.rs, polyval/src/backend/clmul.rs, polyval/src/backend/common.rs, polyval/src/backend/pmull.rs, polyval/src/backend/soft32.rs, polyval/src/backend/soft64.rs, polyval/src/lib.rs, polyval/tests/lib.rs
This MR adapts code from @ericlagergren with permission (see #225) to speed up polyval and ghash.
I expect there are still some performance gains to be had, but this is already fairly well improved: I'm seeing ~~4.3x~~ 7.5x improvement for large inputs on my Alder Lake x86_64 CPU, and 10x improvement on my Apple M1 ARM CPU.
Because this pipelining is not always appropriate (notably, when you know that you will only be handling small inputs), I've also imitated polyval-rs by making the number of blocks to parallelize a generic parameter.
I experimented with manually unrolling the loops here, but I didn't see a performance gain.
=> polyval+ghash: large performance improvements via better instruction-level parallelism
